### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [p-x9/pock-timer-widget#2]
An error occurred during the process.

error.invalid-bundle

<img width="685" alt="image" src="https://user-images.githubusercontent.com/20021695/133627000-2594b00a-d3f7-48a7-aa5e-ce84a3e9ec72.png">

**Comment by p-x9** [comment]
Please use the older version of Pock.app or build this source code yourself.
I think it's due to a bug in the binary that is available on the site.

**Comment by p-x9** [comment]
Fixed this issue [version 2.0.0](https://github.com/p-x9/pock-timer-widget/releases/tag/v2.0.0).
